// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIU5pzEl7CKpZxBnzh4dm5cFjyd_9rLoo',
    appId: '1:1057400678827:web:0b8f4fc5ef8e9019cd8aee',
    messagingSenderId: '1057400678827',
    projectId: 'gastroviaapp',
    authDomain: 'gastroviaapp.firebaseapp.com',
    storageBucket: 'gastroviaapp.firebasestorage.app',
    measurementId: 'G-JMXRVZBK9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAI7jjgHMTdmt3RAxhm0gzWE-22kpHmO0',
    appId: '1:1057400678827:android:65ca8e95bba8ea68cd8aee',
    messagingSenderId: '1057400678827',
    projectId: 'gastroviaapp',
    storageBucket: 'gastroviaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmNdYAUl5s0NwuWQwYeHS9F7EueDdYHko',
    appId: '1:1057400678827:ios:f6c8c054172f9779cd8aee',
    messagingSenderId: '1057400678827',
    projectId: 'gastroviaapp',
    storageBucket: 'gastroviaapp.firebasestorage.app',
    iosBundleId: 'com.example.gastroviaV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmNdYAUl5s0NwuWQwYeHS9F7EueDdYHko',
    appId: '1:1057400678827:ios:f6c8c054172f9779cd8aee',
    messagingSenderId: '1057400678827',
    projectId: 'gastroviaapp',
    storageBucket: 'gastroviaapp.firebasestorage.app',
    iosBundleId: 'com.example.gastroviaV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIU5pzEl7CKpZxBnzh4dm5cFjyd_9rLoo',
    appId: '1:1057400678827:web:faedaa8bee159868cd8aee',
    messagingSenderId: '1057400678827',
    projectId: 'gastroviaapp',
    authDomain: 'gastroviaapp.firebaseapp.com',
    storageBucket: 'gastroviaapp.firebasestorage.app',
    measurementId: 'G-HJM6HGTV1G',
  );
}
